### ISSUE TITLE
libsubstrate.so not found

### ISSUE THREAD

**Issue by ghost** [Mivik/GetDex#1]
My device is android 11, tried in android 8.1 and same issue

**Comment by Mivik** [comment]
You could try to remove line 32-35 in [GetDex.kt](https://github.com/Mivik/GetDex/blob/master/app/src/main/kotlin/com/mivik/getdex/GetDex.kt)

**Comment by gabcodedev** [comment]
I did that and same issue

**Comment by ghost** [comment]
Now it says libgetdex.so is 32 bit instead of 64 bit

**Comment by Mivik** [comment]
The second issue you mentioned is caused by that your target application uses 64-bit libraries but substrate only supports 32-bit. You should re-install the target app by

```shell
adb install --abi armeabi-v7a [apk-file]
```

to make sure it uses 32-bit libraries.

**Comment by Mivik** [comment]
@gabcodedev Hey there! Please let me know if the problem is solved or not, or I'll close this issue for being inactive for long. Thank you for your cooperation!
